generatorName: go

gitHost: github.com
gitUserId: greatman
gitRepoId: go-netbox/v4
packageName: netbox
generateInterfaces: true
disallowAdditionalPropertiesIfNotPresent: false
globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
typeMappings:
  integer: int64
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  packageVersion: "3"
  enumClassPrefix: true
