generatorName: go

gitHost: github.com
gitUserId: greatman
gitRepoId: go-netbox/v4
generateInterfaces: true
packageName: netbox
disallowAdditionalPropertiesIfNotPresent: false
globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  packageVersion: "3"
  enumClassPrefix: true
